## NEONutilities file into one server...

base::source('neonScripts/loadByProduct.R', local=TRUE)   
base::source('neonScripts/zipsByProduct.R', local=TRUE)
base::source('neonScripts/getAPI.R', local=TRUE)
base::source('neonScripts/getZipUrls.R', local=TRUE)
base::source('neonScripts/convByteSize.R', local=TRUE)   
base::source('neonScripts/stackByTable.R', local=TRUE)   
base::source('neonScripts/unzipZipfileParallel.R', local=TRUE)   
base::source('neonScripts/stackDataFilesParallel.R', local=TRUE)   
base::source('neonScripts/table_types.R', local=TRUE)
base::source('neonScripts/findDatatables.R', local=TRUE)   
base::source('neonScripts/findTablesByFormat.R', local=TRUE)   
base::source('neonScripts/getRecentPublication.R', local=TRUE)   
base::source('neonScripts/getVariables.R', local=TRUE)   
base::source('neonScripts/makePosColumns.R', local=TRUE)   
base::source('neonScripts/assignClasses.R', local=TRUE)   

## others...
base::source('neonScripts/byFileAOP.R', local=TRUE)   
base::source('neonScripts/byTileAOP.R', local=TRUE)   
base::source('neonScripts/chem_bundles.R', local=TRUE)   
base::source('neonScripts/cleanUp.R', local=TRUE)   
base::source('neonScripts/dateConvert.R', local=TRUE)   
base::source('neonScripts/findTablesUnique.R', local=TRUE)   
base::source('neonScripts/footRaster.R', local=TRUE)   
base::source('neonScripts/getAPI.R', local=TRUE)   
base::source('neonScripts/getAvg.R', local=TRUE)   
base::source('neonScripts/getDatatable.R', local=TRUE)   
base::source('neonScripts/getFileUrls.R', local=TRUE)   
base::source('neonScripts/getPackage.R', local=TRUE)   
base::source('neonScripts/getProductInfo.R', local=TRUE)   
base::source('neonScripts/getProductSensors.R', local=TRUE)   
base::source('neonScripts/getReadmePublicationDate.R', local=TRUE)   
base::source('neonScripts/getTaxonTable.R', local=TRUE)   
base::source('neonScripts/getTileUrls.R', local=TRUE)   
base::source('neonScripts/getTimeIndex.R', local=TRUE)   
base::source('neonScripts/getVarsEddy.R', local=TRUE)   
base::source('neonScripts/listFilesInZip.R', local=TRUE)
base::source('neonScripts/listZipfiles.R', local=TRUE)
base::source('neonScripts/getTitle.R', local=TRUE)
base::source('neonScripts/quietMessages.R', local=TRUE)
base::source('neonScripts/readTableNEON.R', local=TRUE)
base::source('neonScripts/shared_aquatic.R', local=TRUE)
base::source('neonScripts/shared_flights.R', local=TRUE)
base::source('neonScripts/stackEddy.R', local=TRUE)
base::source('neonScripts/stackFromStore.R', local=TRUE)
base::source('neonScripts/transformFileToGeoCSV.R', local=TRUE)
base::source('neonScripts/unzipZipfileParallel.R', local=TRUE)
base::source('neonScripts/zipsByURI.R', local=TRUE)

load('neonScripts/sysdata.rda')
load('data/shared_aquatic.rda')
load('data/chem_bundles.rda')
load('data/table_types.rda')
load('data/shared_flights.rda')
